apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-sizing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-sizing
  template:
    metadata:
      labels:
        app: atlas-sizing
    spec:
      containers:
      - name: atlas-sizing
        image: docker.io/shashirsb/sizingatlas:11
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "https://ec2-35-171-28-135.compute-1.amazonaws.com:3000/fetchLatestSizing"
      imagePullSecrets:
      - name: docker-secret    
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-sizing-service
spec:
  selector:
    app: atlas-sizing
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer